export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRECT_USER = 'SET_CURRECT_USER';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_CURRENT_COMPANY = 'CLEAR_CURRECT_COMPANY';
export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANIES = 'GET_COMPANIES';
export const COMPANY_LOADING = 'COMPANY_LOADING';
export const COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND';
